server:
  port: 9090
spring:
  profiles:
    active: dev
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
      encoding: UTF-8
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/dbfile
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    print-banner: false
  mapper-locations:
    - "classpath*:/mapper/*.xml"
  type-aliases-package: com.zclcs.erp.api.bean.entity

open-browser:
  open-url: http://localhost:${server.port}/static/index.html