spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/dbfile
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
  data:
    rest:
      page-param-name: page
      limit-param-name: limit

logging:
  level:
    com.zclcs.erp.configuration.MyBatisFlexConfiguration: debug

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    print-banner: false
  mapper-locations:
    - "classpath*:/mapper/**/*.xml"
  type-aliases-package: com.zclcs.platform.system.api.bean.entity