spring:
  h2:
    console:
      enabled: false
      path: /h2-console

logging:
  level:
    com.zclcs: info
    com.zaxxer: info
    _org.springframework: info
    org.springframework: info
    org.hibernate: info
    org.mybatis: info
    org.apache.ibatis: info
    org.jboss: info

open-browser:
  open: true